### ISSUE TITLE
Is this repo still working? Can't run the colab notebooks provided in the doc

### ISSUE THREAD

**Issue by coldfir3** [butchland/fastai_xla_extensions#37]
Hello, first of all, thank you the hard work of implementing XLA using fastai

I am trying to run the examples under the documentation (without altering any single line) and they just hang when trying to fit a model, no progress bar movement, or anything.

Are those examples still working?

**Comment by butchland** [comment]
Due to an incompatibility with the latest version of fastai  (2.4.1 as of July 2021), we need to pin the fastai version to 2.3.0. 
The sample notebooks have been updated to pin the fastai version to 2.3.0 and should now be all working again. 
@coldfir3 if you still have problems, feel free to reach out to me again.  Sorry for the delayed response. 

Unfortunately I don't have to current bandwidth to find the fix to the incompatibility and allow the latest version of fastai to work with this package, so hopefully the workaround will have to do.
